### ISSUE TITLE
Wireguard Config

### ISSUE THREAD

**Issue by Kashif-Asghar60** [Wachu985/flutter_wireguard_vpn#2]
Thank You for the plugin , I'm new to vpn environment. I dont know where to get the configs for the wireguard.
Can you guide me how to obtain the a ddress, Port , DnsServer, PrivateKey, PublicKey, Endpoint ,presharedKey etc.
It would be nice if you include this in readme.md.

**Comment by flowan** [comment]
Via the website [`https://www.wireguardconfig.com`](https://www.wireguardconfig.com) you can generate server and client configs. Hope this helps.

**Comment by Kashif-Asghar60** [comment]
@flowan  Thanks for the help mate but I figured that already.

**Comment by Wachu985** [comment]
> 

Thank you for the comment. I've added a section in the README.md to provide information on obtaining WireGuard configurations.
