### ISSUE TITLE
Release mode not working 

### ISSUE THREAD

**Issue by Kashif-Asghar60** [Wachu985/flutter_wireguard_vpn#3]
Release mode not working , when i click to toggle switch i get errors in release mode. Works fine for debug mode.
And are there any plans for IOS support?

**Comment by Wachu985** [comment]
> Release mode not working , when i click to toggle switch i get errors in release mode. Works fine for debug mode. And are there any plans for IOS support?

The solution has been added to the README.md thanks to user @ByteSizedMarius. Regarding the iOS version, I currently lack the resources and knowledge to develop it. Perhaps in the future, I might be able to work on it. However, feel free to contribute to the package if you're interested.
